### ISSUE TITLE
Vytvořit tisknutelnou krabičku pro CUAV GPS NEO V2

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/Hardware#16]
Nakrslit tisknutelnou krabičku pro CUAV GPS s vhodnými montážními otvory. 

Při prvním použití se tato krabička zřejmě připevní pomocí suchého zipu na podložku vírníku.

Potřebné rozměry jsou patrné z následujících obrázků. 

![20190706_094153](https://user-images.githubusercontent.com/5196729/60753529-1ffbf580-9fd4-11e9-9f90-b7a0d7114d34.jpg)
![20190706_094346](https://user-images.githubusercontent.com/5196729/60753531-25594000-9fd4-11e9-9408-584d0ffcf145.jpg)
![20190706_094429](https://user-images.githubusercontent.com/5196729/60753532-2a1df400-9fd4-11e9-9b73-7ed280a97890.jpg)
![20190706_094444](https://user-images.githubusercontent.com/5196729/60753533-2db17b00-9fd4-11e9-9c55-a4fa6a5d7f17.jpg)
![20190706_094457](https://user-images.githubusercontent.com/5196729/60753542-40c44b00-9fd4-11e9-8f8f-67c726f1544a.jpg)
![20190706_094517_HDR](https://user-images.githubusercontent.com/5196729/60753550-533e8480-9fd4-11e9-959a-f07329920fc2.jpg)

**Comment by roman-dvorak** [comment]
Existuje základní díly krabičky pro CUAV GPS. Nyní je potřeba na krabičce vyřešit několik problémů:

- [ ] Vytvořit otvor pro GPS FIX led, která je umístěna na vrchní straně PCB. vedle antény. Její polohu lze nejlépe určit z fotek. Otvor by mohl obsahovat vytištěný světlovod. Tím dojde i k zodolnění proti vodě. 
- [ ] Vytvořit otvor pro SafetySwitch led.
- [ ] Zajistit nemožnost vytržení kabelu z konektoru. Na kabel by tam měla být nějaká svorka, která se ke krabičce přišroubuje klidně z boku
- [ ] Ověřit správnost velikosti otvorů pro šrouby

![20190719_105458](https://user-images.githubusercontent.com/5196729/61523298-56923100-aa14-11e9-8565-c57e3e49ae0c.jpg)

![20190719_105352](https://user-images.githubusercontent.com/5196729/61523304-5abe4e80-aa14-11e9-9e47-0fdb003854eb.jpg)

![20190719_105253_HDR](https://user-images.githubusercontent.com/5196729/61523308-5db93f00-aa14-11e9-9e1a-cda463d3031e.jpg)

**Comment by roman-dvorak** [comment]
- [ ] Použít M2.5 x 12 šrouby
- [ ] Zvětšit vnitřní poloměr části pro led o 2 mm
- [ ] Vytvořit díry pro šrouby
- [ ] Zmenšit prostor v horní části

**Comment by roman-dvorak** [comment]
Do dílu je potřeba přidělat M3 montážní otvory, aby krabičku bylo možné připevnit do univerzálních drážek nového nosníku.

**Comment by kaklik** [comment]
Řekl bych, že tuhle GPS zřejmě nebudeme nadále používat, tak je asi zbytečné krabičku dále vylepšovat.
