### ISSUE TITLE
Zkontrolovat parametry pro M2.5

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/Hardware#17]
Zkontrolovat parametry ve všech parametrických souborech pro M2.5 šrouby a matice. Nezná se mi poměr jejich hodnot. U GPS krabičky jsou nově použity M2.5 šrouby. Průměr jejich matic oproti průměru díry pro šroub se mi zdá velmi malý. Je možné, že jsou tolerance špatně nastaveny/zapomenuty

**Comment by roman-dvorak** [comment]
![Snímek z 2019-09-06 07-18-45](https://user-images.githubusercontent.com/5196729/64402995-23b10480-d077-11e9-9d71-134d0d72ed96.png)

**Comment by kaklik** [comment]
Myslím, že je poměrně důležité u nových dílů přecházet na parametrickou knihovnu šroubů: https://github.com/ThunderFly-aerospace/TF-G1/tree/improved_suspension/src/lib

aby parametry šroubů nebyly v parametrickém souboru modelů/sestavy.

**Comment by roman-dvorak** [comment]
Parametr je nyní správně.
