### ISSUE TITLE
Oproti současnému řešení použít lepší konektory

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/Hardware#2]
Molex konektory nejsou moc vhodné. 

Zdá se, že pro interní konektory je lepší novější standard. 
https://wiki.dronecode.org/workgroup/connectors/start

Je ale potřeba ověřit zda od tohoto typu konektorů existuje THT verze.  Protože SMD verze konektorů se z desky bude téměř jistě trhat.

**Comment by ChroustJan** [comment]
Protikus konektoru:
http://www.jst-mfg.com/product/detail_e.php?series=105

**Comment by kaklik** [comment]
Trochu se obávám, že od toho konektoru neexistuje THT verze do PCB, ale usuzuji to jenom z tohoto datasheetu, kde není nakreslená: http://www.jst-mfg.com/product/pdf/eng/eGH.pdf

**Comment by kaklik** [comment]
Vidím to tak, že je zřejmě potřeba použít ty JST GH konektory, které jsou SMT, s tím že musíme udělat desku, která bude stále ještě kompatibilní s existujícím řešením. Aby se stala používaná i někde jinde než u nás.  Pak můžeme udělat další verzi třeba s lepšími konektory. Pokud se to budeme snažit zlepšit rovnou, tak ta deska nebude přijmuta komunitou a budeme na to sami.

**Comment by ChroustJan** [comment]
Opravdu to chceme? Nejde nám především o kvalitní UAV?

**Comment by kaklik** [comment]
JST-GH konektory jsou nakonec překvapivě dobré.
