### ISSUE TITLE
I2C extender

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/Hardware#23]
V Pixhawk systému zřejmě chybí nástroj, jak prodlužovat vodiče I2C sběrnice. Zřejmě by to měl být modul, který na protilehlých hranách bude mít běžné JST-GH konektory používané pro I2C. 

Funkci modulu lze odvodit od existujících extenderů používaných pro jiné aplikace:

- [poneti2cextender](https://www.poscope.com/product/poneti2cextender/) - zřejmě využívá obvod P82B715.
- [Adafruit LTC4311 I2C Extender](https://blog.adafruit.com/2020/10/14/new-guide-adafruit-ltc4311-i2c-extender-active-terminator-adafruitlearningsystem-stemma-adafruit/)
- https://store.ncd.io/product/p82b715td-long-distance-i2c-bus-extender-i2c-mini-module/ - využívá P82B715

Samostatné obvody:
- [PCA9600](https://www.nxp.com/products/interfaces/ic-spi-serial-interface-devices/ic-bus-repeaters-hubs-extenders/dual-bidirectional-bus-buffer:PCA9600) - rozděluje SDA a SCL signály na unidirictional TX a RX signály
- [LTC4311](https://www.analog.com/en/products/ltc4311.html#product-overview) - vzhledem principu funkce se mi nezdá, že takové řešení bude spolehlivé v kombinaci s [TFASPDIMU01](https://github.com/ThunderFly-aerospace/TFASPDIMU01), který už rise-time akcelerátor obsahuje sám o sobě. Mohlo by dojít k vzájemnému rozkmitání v nedefinovaných situacích.
- [P82B715]( https://www.nxp.com/docs/en/data-sheet/P82B715.pdf) Potřebuje stejný obvod symetricky na obou koncích sběrnice. 
- [P82B96](https://www.ti.com/product/P82B96) - Rozděluje signály na RX, TX s mírně odlišnými logickými úrovněmi. 
- TCA4307

**Comment by ChroustJan** [comment]
@kaklik jako zásadní vidím výběr vhodného IO. A pak mechanickou konstrukci. Očekávám, že to budeme chtít malé.

**Comment by kaklik** [comment]
Zvolen obvod [TCA4307](https://www.ti.com/product/TCA4307)
