### ISSUE TITLE
Výběr senzorů do nové verze hardaware FMUv5

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/Hardware#7]
Aktuálně máme tuto tabulku, která pokrývá senzory předchozích verzí hardware autopilota ze [seznamu hardware](https://docs.px4.io/en/flight_controller/pixhawk_series.html)

| Typ senzoru        | Zaletovatelný | Má driver |  Jde koupit | Poznamka |
| ------------- |:-------------:|:-----:|:-----:| ------------------------------------- |
| **gyroskopy, akcelerometry (IMU)** | | ||
| BMI055 |  | X | X ||
| ICM-20602 | | X | X ||
|ICM-20689 | X | X | X ||
|MPU-6000| X | X | X||
|[MPU-9250](https://www.invensense.com/products/motion-tracking/9-axis/mpu-9250/)| X | ? | NRND||
| **tlakoměry**  | |  |  ||
| [MS5611](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS5611-01BA03%7FB3%7Fpdf%7FEnglish%7FENG_DS_MS5611-01BA03_B3.pdf%7FCAT-BLPS0036) | X | X | X ||
| **Magnetometry** |  | | ||
| [IST8310](www.isentek.com/en/dlf.php?file=../ISENTEK/(201703-09)IST8310%20Datasheet%20v1.2_brief-105.09.20.pdf) |  | X |  |   |
| [bmm150](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BMM150-DS001-01.pdf)| |X| ? | |
| [hmc5883](https://cdn-shop.adafruit.com/datasheets/HMC5883L_3-Axis_Digital_Compass_IC.pdf)|  | X |  | již se nevyrábí |
| [mmc5883](http://www.memsic.com/userfiles/files/DataSheets/Magnetic-Sensors-Datasheets/MMC5883MA-RevC.pdf)|  | X | X |  |
| [LIS3MDL](https://www.st.com/resource/en/datasheet/lis3mdl.pdf)|  | X | ? ||
| [LSM303AGR](https://www.st.com/resource/en/datasheet/lsm303agr.pdf) |   |X | ? ||
| [RM3100](https://www.pnicorp.com/download/rm3100-user-manual/?wpdmdl=5678&ind=38LVTMp6fKZwfFcc6dqLrt7I_xO-3kl2CPQdkBNUW8K-SIiXdqh5hnDXHz1l0C0ARVgyLUj68STLEE4PxMs6oQ) | X | X | ? | Externí cívky, nenašel jsem normální obchod |
| [ICM-20948](https://cz.mouser.com/datasheet/2/400/DS-000189-ICM-20948-v1.3-1385562.pdf) | - | X | X |  |
| [MLX90393](https://www.melexis.com/en/product/MLX90393/Triaxis-Micropower-Magnetometer) | X | - | X | Nízká citlivost |
| [IIS2MDC](https://www.st.com/en/mems-and-sensors/iis2mdc.html) |  | - | X | |
| [BM1422GMV](https://www.rohm.com/documents/11303/4214223/BM1422GMV-e.pdf/ed4dd471-75fc-40d2-bbb0-879b0cb249c2) |  | - |  | |
| [KMX62-1031](http://kionixfs.kionix.com/en/document/KMX62-1031-Specifications-Rev-4.0.pdf) | ? | - | X | |
| [AK09915C](https://www.akm.com/akm/en/file/datasheet/AK09915C.pdf) | ? | - | X | |
| [AK09918C](https://www.akm.com/akm/en/file/datasheet/AK09918C.pdf) | ? | - | X | |

Je potřeba: 

- [x] Najít podporovaný magnetometr, který dokážeme koupit a zeletovat
- [x] Zjistit jak se zpracovávají data z IMU snímačů z hlediska redundance a zda je tam nějaký mechanismus, který data filtruje a kombinuje z více snímačů. Podle toho určíme, kolik IMU čidel na autopilotovi potřebujeme.

**Comment by slimonslimon** [comment]
Pořadí vyhodnocování kritérií magnetometru - Driver - Pouzdro - dá se koupit

**Comment by kaklik** [comment]
Tak podle toho co z kódu analyzoval @slimonslimon to vypadá, že se za provozu vyčítá pouze jeden senzor s největší prioritou a nejvyšší věrohodností (s nejnižším počtem nahlášených vlastních chyb). 
To znamená, že zde není implementován žádný chytrý algoritmus dynamické volby nejlepší měřené hodnoty, ale pouze se čeká až zvolený senzor selže. Do té doby se nic neděje.

Z toho vyplývá, že potřebujeme, aby autopilot měl 3 různé senzory s vhodným pouzdrem. A nyní alespoň 2 z nich podporované firmwarem, abychom se nepřipravili o současnou bezpečnost poskytovanou možností přepnout na záložní senzor. 

Třetí senzor by pak sloužil pro implementaci lepšího algoritmu volby měřené hodnoty v budoucnu.

**Comment by slimonslimon** [comment]
ta chyba se tam počítá nějak kumulativně, když pak zase měří a nehlásí senzor chyby tak se snižuje....

**Comment by kaklik** [comment]
@ChroustJan podle téhle tabulky je zřejmě už nedořešený pouze výběr magnetometru a ta nedořešenost je způsobená tím, že jsme nikdo zatím nedovedl najít magnetometr, který by splňoval výše uvedená kritéria.

**Comment by kaklik** [comment]
Pro IMU  by zřejmě nejprofesionálnější řešení bylo použití něčeho, jako je tenhle modul: 
https://www.analog.com/en/products/adis16405.html

V případě současného vírníku to ale zřejmě není řešení potíží výběrem vhodného magnetometru.

**Comment by kaklik** [comment]
Myslím, že magnetometr je nalezený ICM-20948
